services:
  db:
    image: postgres:17.6
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=travel_todo_db"
      - "POSTGRES_USER=guest"
      - "POSTGRES_PASSWORD=hello_guest"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/main/resources/certs/travel-todo-api-455519588477.asia-northeast3.run.app.test+3.pem:/var/lib/postgresql/server.crt:ro
      - ./src/main/resources/certs/travel-todo-api-455519588477.asia-northeast3.run.app.test+3-key.pem:/var/lib/postgresql/server.key:ro
    # Using a shell script to fix permissions at runtime
    entrypoint: >
      sh -c "
      cp /var/lib/postgresql/server.key /tmp/server.key &&
      chown postgres:postgres /tmp/server.key &&
      chmod 600 /tmp/server.key &&
      exec docker-entrypoint.sh postgres 
      -c ssl=on 
      -c ssl_cert_file=/var/lib/postgresql/server.crt 
      -c ssl_key_file=/tmp/server.key
      "
volumes:
  pgdata:
