spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: src/main/resources/temp/V1__initial_schema.sql
            create-source: metadata
  flyway:
    enabled: false