spring:
  profiles:
    group:
      local:
        - dev
        - ssl
      prod:
        - ai
      test:
        - dev
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    baseline-on-migrate: true
  datasource:
    driver-class-name: org.postgresql.Driver
#    hikari:
#      keepalive-time: 30000
#      max-lifetime: 600000
#      connection-test-query: SELECT 1
#      initialization-fail-timeout: 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  security:
    oauth2:
      resourceserver:
        jwt:
          kakao:
            issuer-uri: https://kauth.kakao.com
          google:
            issuer-uri: https://accounts.google.com
  session:
    jdbc:
      initialize-schema: always
  cloud:
    gcp:
      project-id: ${GOOGLE_CLOUD_PROJECT}
  ai:
    openai:
      api-key: fake-spring-ai-openai-api-key
      base-url: replace-this-with-mock-server-base-url
#  cache:
#    jcache:
#      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
#    cache-names:
#      - create-reservation-from-text-api-call-quota-cache
#    caffeine:
#      spec: maximumSize=100000,expireAfterAccess=1d
logging:
  level:
    org:
      springframework:
        security: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
  # https://docs.spring.io/spring-boot/reference/actuator/metrics.html#actuator.metrics.customizing.per-meter-properties
  # https://docs.spring.io/spring-boot/reference/actuator/metrics.html#actuator.metrics.supported.spring-mvc
  metrics:
    enable:
      all: false
      http.server.requests: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
app:
  quota:
    max-trips: 5
    max-trip-duration-days: 60
    max-destinations: 4
    max-todos: 64
    max-reservations: 64



# @TODO: use redis, not caffeine.
bucket4j:
  enabled: false
#  filter-config-caching-enabled: false
#  filters:
#    - cache-name: create-reservation-from-text-api-call-quota-cache
#      url: ^/trip/[^/]+/reservation/analysis/text.*
#      filter-method: servlet
#      filter-order: 1
#      rate-limits:
#        # @TODO: use user account id as cache key (Current approach: ip address as cache key)
#        - cache-key: "@securityService.getUserId() ?: getRemoteAddr()"
#          bandwidths:
#            - capacity: 2
#              time: 30
#              unit: days
#              refill-speed: interval
#        #   execute-predicates:
#        #     - METHOD=GET
#        #     - METHOD=POST
