spring:
  ai:
    model:
      chat: google-genai
    retry:
      max-attempts: 1
    google:
      genai:
        #        project-id: ${SPRING_AI_GOOGLE_GENAI_PROJECT_ID}
        #        api-key: ${SPRING_AI_GOOGLE_GENAI_API_KEY}
        chat:
          options:
            model: gemini-3-flash-preview
            temperature: 0.1
            thinking-level: LOW
