package main

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var latencyHistogram = promauto.NewHistogram(prometheus.HistogramOpts{
	Name: "latency_sampler_duration_seconds",
	Help: "Latency generated by the sampler in seconds.",
	// Set this factor to enable dynamic native histograms.
	// 1.1 gives ~10% resolution between buckets without manual setup.
	NativeHistogramBucketFactor: 1.1,
})
