FROM public.ecr.aws/lambda/java:21

# Add Lambda Web Adapter
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.9.1 /lambda-adapter /opt/extensions/lambda-adapter

# Copy and extract zip contents (ADD automatically extracts zip files)
ADD .docker/dist/lambda-app.zip /var/task/

# Run your script
CMD ["run.sh"]
