name: Pull Request CI

on:
  pull_request:
    branches: [ "develop", "staging", "ci/pr-check-test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          java-version: '21'
          distribution: 'temurin'

# Deprecated: grant permission permanently in git context instead of this.
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew

      - name: Build and Test
        run: ./gradlew build --no-daemon # Use --no-daemon for CI environments to prevent memory leaks

      - name: Upload Test Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests/test/**